version: 0.6.0
backend:
  url:
  public_socket_url:
  public_content_url:

mailer:
  from: 'aida@instedd.org'
  delivery_method: smtp

smtp_settings:
  # user_name:
  # password:
  # address:
  # domain:
  # port:
  # authentication:

base_url:
